routes/web.php
<?php


Route::get('/', function () {
	return view('welcome');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin'], function() {
    Route::get('/', function() {
        return view('dashboard.index');
    });
	
	//CRUD Usuarios
	Route::resource('users', 'UserController');

	//Roles
	Route::resource('roles', 'RoleController');

	//Menus
	require __DIR__.'/admin/menu_route.php';

});

Route::group(['prefix' => 'reception', 'middleware' => 'auth'], function() {
    //Clientes Routes
	Route::resource('clients', 'Admin\ClientController');
	
	//Generate List and update "Orders"
	require __DIR__.'/reception/orders_route.php';

});

Route::group(['prefix' => 'settings', 'namespace' => 'Settings'], function() {
    Route::resource('lines', 'LineController');
});

//Perfil de usuario logeado
Route::get('profile', [
		'uses' => 'ProfileController@index',
		'as' => 'profile.index',
]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use Miyama\Address;
use Illuminate\Http\Request;
use Miyama\Admin\Client;
use App\QueryFilters\ClientFilters;
use App\Http\Controllers\Controller;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(ClientFilters $filters)
    {
        $clients = Client::orderBy('id', 'DESC')
            ->with('addresses', 'addresses.state', 'addresses.city')
            ->filter($filters)
            ->paginate();
        
        return view('admin.clients.index',compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'type_identification' => 'required',
            'identification' => 'required',
            'business_name' => 'required',
            'mobil' => 'required',
            'email' => 'required',
        ]);

        $client = Client::create($request->all());

        //$client->addresses()->create($request->all());
        
        return redirect()->route('clients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($client)
    {   
        $client = Client::with('orders', 'orders.status', 'orders.product')
                        ->find($client);

        return view('admin.clients.show', compact('client'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('admin.clients.edit', compact('client'));        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $client->update($request->all());
        $client->addresses()->first()->update($request->all());

        \Alert::info('El cliente fue editado correctamente.');
        
        return redirect()->route('clients.show', ['id' => $client->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/clients/create.blade.php
@extends('layouts.template')

@section('page-heading')
<i class="si si-users"></i> Nuevo Cliente
@endsection

@section('content')
<div class="block block-themed block-rounded">
	<div class="block-header bg-primary">
		<h3 class="block-title">Datos del Cliente</h3>
	</div>
	<div class="block-content">
	{{ Form::open(['mehtod'=>'POST', 'route' => 'clients.store']) }}
		<div class="row">
			<div class="col-md-2">
				{!! Field::select('type_identification', ['V'=>'V', 'J'=>'J', 'G'=>'G']) !!}
			</div>
			<div class="col-md-3">
				{!! Field::text('identification', ['placeholder' => '19747349']) !!}
			</div>
			<div class="col-md-7">
				{!! Field::text('business_name', ['placeholder' => 'Jose Luis']) !!}					
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				{!! Field::text('email', ['placeholder' => 'ejemplo@gmail.com']) !!}
			</div>
			<div class="col-md-4">
				{!! Field::text('phone', ['placeholder' => '02642617878']) !!}
			</div>
			<div class="col-md-4">
				{!! Field::text('mobil', ['placeholder' => '04149023212']) !!}
			</div>
		</div>

		@include('layouts.form.address-inputs')

		<div class="form-group">
			<button class="btn btn-primary"><i class="fa fa-save"></i> Guardar</button>
			<a href="/admin" class="btn btn-default"><i class="fa fa-"></i> Salir</a>
		</div>
	{{ Form::close() }}
	</div>
</div>
@endsection

resources/views/admin/clients/edit.blade.php
@extends('layouts.template')

@section('page-heading')
<i class="si si-users"></i> Editar Clientes 
@endsection

@section('content')
<div class="block block-themed block-rounded">
	<div class="block-header bg-primary">
		<h3 class="block-title">Datos del Cliente</h3>
	</div>
	<div class="block-content">
	{{ Form::open(['method'=>'PUT', 'url' => route('clients.update', ['id' => $client->id])]) }}
		<div class="row">
			<div class="col-md-2">
				{!! Field::select('type_identification', ['V'=>'V','J'=>'J','G'=>'G'], $client->type_identification) !!}
			</div>
			<div class="col-md-3">
				{!! Field::text('identification', $client->identification,['placeholder' => '19747349']) !!}
			</div>
			<div class="col-md-4">
				{!! Field::text('business_name', $client->business_name, ['placeholder' => 'Lujan Rodriguez']) !!}
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				{!! Field::text('email', $client->email, ['placeholder' => 'ejemplo@gmail.com']) !!}
			</div>
			<div class="col-md-4">
				{!! Field::text('phone', $client->phone, ['placeholder' => '02642617878']) !!}
			</div>
			<div class="col-md-4">
				{!! Field::text('mobil', $client->mobil,['placeholder' => '04149023212']) !!}
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				{!! Field::select('state_id', $states,  $client->addresses->first()->state->id) !!}
			</div>
			<div class="col-md-4">
				{!! Field::select('city_id', $client->addresses->first()->state->cities_now, $client->addresses->first()->city->id) !!}
			</div>
			<div class="col-md-4">
				{!! Field::text('address', $client->addresses->first()->address,['placeholder' => 'Urb Los Laureles Secto 8 #32']) !!}
			</div>
		</div>

		<div class="form-group">
			<button class="btn btn-primary"><i class="fa fa-save"></i> Guardar</button>
			<button class="btn btn-default"><i class="fa fa-"></i> Salir</button>
		</div>
	{{ Form::close() }}
	</div>
</div>
@endsection

resources/views/admin/clients/index.blade.php
@extends('layouts.template')

@section('page-heading')
<i class="si si-users"></i> Clientes 
@endsection

@section('content')
<div class="block block-themed block-rounded">
	<div class="block-header bg-primary">
		<div class="block-options-simple btn-group btn-group-xs">
			<a href="{{ route('clients.create') }}" class="btn btn-default"><i class="si si-plus"></i> Crear</a>
		</div>
		<h3 class="block-title">Lista de Clientes</h3>
	</div>
	<div class="">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Identificacion</th>
				<th>Razon Social</th>
				<th>Email</th>
				<th>Telefonos</th>
				<th>Accion</th>
			</tr>
		</thead>
		<tbody>
			@foreach($clients as $client)
				<tr>
					<td>{{ $client->full_identification }}</td>
					<td>{{ $client->business_name }}</td>
					<td>{{ $client->email }}</td>
					<td>
						{{ $client->mobil }} /
						{{ $client->phone }}
					</td>
					<td>
						<div class="btn-group">
	                        <div class="btn-group">	                            
	                            <a href="{{ route('clients.show', ['id'=> $client->id]) }}" class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="top" title type="button" data-original-title="Ver clinete">
	                            	<i class="fa fa-eye"></i>
	                            </a>
	                            <a href="{{ route('clients.edit', ['id'=> $client->id]) }}" class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="top" title type="button" data-original-title="Editar cliente">
	                            	<i class="fa fa-edit"></i>
	                            </a>
	                            <a href="{{ route('order.create', ['id'=> $client->id]) }}" class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="top" title type="button" data-original-title="Generar nueva orden">
	                            	<i class="si si-wrench"></i>
	                            </a>
	                        </div>
	                    </div>
					</td>
				</tr>
			@endforeach			
		</tbody>
	</table>
	</div>
	{!! $clients->links() !!}
</div>
@endsection

resources/views/admin/clients/show.blade.php
@extends('layouts.template')

@section('page-heading')
<i class="icon-users"></i> Cliente
@endsection

@section('content')

<div class="block block-themed block-rounded">
	<div class="block-header bg-primary">
		<div class="block-options-simple btn-group btn-group-xs">
			<a href="{{ route('clients.edit', ['id'=> $client->id]) }}" 
				class="btn btn-sm btn-default" 
				data-toggle="tooltip" 
				data-placement="top" 
				title type="button" 
				data-original-title="Editar cliente">
        		<i class="fa fa-edit"></i>
        	</a>
        	
        	<a href="{{ route('order.create', ['id'=> $client->id]) }}" 
        		class="btn btn-sm btn-default" 
        		data-toggle="tooltip" 
        		data-placement="top" 
        		title type="button" 
        		data-original-title="Generar nueva orden">
        		<i class="si si-wrench"></i>
	        </a>
		</div>
		<h3 class="block-title">Datos de Cliente</h3>
	</div>
	<div class="">
		<table class="table table-condensed">
			<tbody>
				<tr>
					<th>Identificacion</th>
					<th>Razon Social</th>
					<th>Email</th>
				</tr>
				<tr>
					<td>{{ $client->full_identification }}</td>
					<td>{{ $client->business_name }}</td>
					<td>{{ $client->email }}</td>
				</tr>
				<tr>
					<th>Telefonos</th>
					<th colspan="2">Direccion</th>
				</tr>
				<tr>
					<td>{{ $client->mobil }} / {{ $client->phone }}</td>
					<td colspan="2">{!! $client->full_address !!}</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<div class="block block-themed block-rounded">
	<div class="block-header bg-info">
		<h3 class="block-title"><small><i class="si si-wrench"></i></small> Ordenes</h3>
	</div>
	<div class="">
		<table class="table table-condensed ">
			<thead>
				<tr>
					<th>#</th>
					<th>Articulo</th>
					<th>Serial</th>
					<th>Tecnico</th>
					<th>Estatus</th>
					<th>Accion</th>
				</tr>
			</thead>
			<tbody>
			@foreach($client->orders as $order)
				<tr>
					<td>{{ $order->id }}</td>
					<td>{{ $order->product->name }}</td>
					<td>{{ $order->serial }}</td>
					<td>{{ $order->tech_id }}</td>
					<td>{!! $order->statu !!}</td>
					<td><span class="label bg-primary">Revision</span></td>
					<td>
						<a href="{{ route('orders.show', ['id'=> $client->id]) }}" class="btn btn-success btn-sm"><i class="fa fa-eye"></i></a>
					</td>
				</tr>
			@endforeach
			</tbody>
		</table>
	</div>
</div>

@endsection