routes/web.php
<?php


Route::get('/', function () {
	return view('welcome');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin'], function() {
    Route::get('/', function() {
        return view('dashboard.index');
    });
	
	//CRUD Usuarios
	Route::resource('users', 'UserController');

	//Roles
	Route::resource('roles', 'RoleController');

	//Menus
	require __DIR__.'/admin/menu_route.php';

});

Route::group(['prefix' => 'reception', 'middleware' => 'auth'], function() {
    //Clientes Routes
	Route::resource('clients', 'Admin\ClientController');
	
	//Generate List and update "Orders"
	require __DIR__.'/reception/orders_route.php';

});

Route::group(['prefix' => 'settings', 'namespace' => 'Settings'], function() {
    Route::resource('lines', 'LineController');
});

//Perfil de usuario logeado
Route::get('profile', [
		'uses' => 'ProfileController@index',
		'as' => 'profile.index',
]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Settings/LineController.php
<?php

namespace App\Http\Controllers\Settings;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Miyama\Products\Line;
use Miyama\Products\SubLine;

class LineController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lines = Line::with('sub_lines', 'sub_lines.products')->get();
        return view('settings.lines.index', compact('lines'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Line::create($request->all());
        return redirect()->route('lines.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Line $line)
    {
        $sub_line = SubLine::make($request->all());
        $line->sub_lines()->save($sub_line);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/settings/lines/index.blade.php
@extends('layouts.template')

@section('page-heading')
<i class="si si-users"></i> Lineas <a class="btn btn-success btn-sm" data-toggle="modal" href='#modal-id'>Agregar Lines</a>
@endsection

@section('content')

<div class="col-md-12">
	<div class="block block-themed block-rounded">
		<div class="block-header bg-primary">
			<div class="block-options-simple btn-group btn-group-xs">
				
			</div>
			<h3 class="block-title">Liena </h3>
		</div>
		<div class="">
			<table class="table">
				<thead>
					<tr>
						<th>Nombre de la Linea</th>
						<th>Sub Lines</th>
					</tr>
				</thead>
				<tbody>
				@foreach($lines as $line)
					<tr>
						<td>{{ $line->name }}</td>
						<td>
							<ul>
								<li><button onclick="$('.new-sub-line-{{$line->id}}').toggle()" class="btn btn-default"><i class="si si-plus"></i> Nueva Sub Linea</button></li>
								<li style="display: none" class="new-sub-line-{{$line->id}}">
									{{ Form::open(['method'=>'PUT','url'=> route('lines.update', ['id' => $line->id])]) }}
										{!! Field::text('name') !!}
									{{ Form::close() }}
								</li>
								@foreach($line->sub_lines as $sub_line)
									<li>{{ $sub_line->name }}</li>
								@endforeach
							</ul>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>
	</div>

<div class="modal fade" id="modal-id">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Nueva Linea</h4>
			</div>
			{{ Form::open(['method' => 'POST','route' => 'lines.store']) }}
			<div class="modal-body">
					{!! Field::text('name') !!}
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="button" class="btn btn-primary">Guardar</button>
			</div>
			{{ Form::close() }}
		</div>
	</div>
</div>
@endsection