routes/web.php
<?php


Route::get('/', function () {
	return view('welcome');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Admin'], function() {
    Route::get('/', function() {
        return view('dashboard.index');
    });
	
	//CRUD Usuarios
	Route::resource('users', 'UserController');

	//Roles
	Route::resource('roles', 'RoleController');

	//Menus
	require __DIR__.'/admin/menu_route.php';

});

Route::group(['prefix' => 'reception', 'middleware' => 'auth'], function() {
    //Clientes Routes
	Route::resource('clients', 'Admin\ClientController');
	
	//Generate List and update "Orders"
	require __DIR__.'/reception/orders_route.php';

});

Route::group(['prefix' => 'settings', 'namespace' => 'Settings'], function() {
    Route::resource('lines', 'LineController');
});

//Perfil de usuario logeado
Route::get('profile', [
		'uses' => 'ProfileController@index',
		'as' => 'profile.index',
]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Orders/GenerateOrderController.php
<?php

namespace App\Http\Controllers\Orders;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use Miyama\Order;
use Miyama\Address;
use Miyama\Admin\Client;
use App\Http\Requests\GenerateOrderRequest;

class GenerateOrderController extends Controller
{

	public function create(Client $client)
	{
		return view('orders.create', compact('client'));
	}

    public function generate(GenerateOrderRequest $request, Client $client)
    {
        $order = $client->orders()->create($request->all());
        
        $this->isDelivery($request, $order);
        
        \Alert::info('La orden fue generada exitosamente');

        return redirect()->route('orders.index');
    }

    protected function isDelivery($request, $order)
    {

        if ($request->domicilio == true) {
            $order->update(['type' => 'delivery']);

            if ($request->type_address == 0) {
                $address = Address::create($request->all());
                $this->attachDelivery($order, $address->id);
            }else{
                $this->attachDelivery($order, $request->type_address);                
            }            
        }
    }
    
    protected function attachDelivery($order, $request)
    {
        $order->addresses()->attach($request);
    }
}

app/Http/Controllers/Orders/OrdersController.php
<?php

namespace App\Http\Controllers\Orders;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Miyama\Order;
use App\QueryFilters\OrderFilters;

class OrdersController extends Controller
{

    public function index(OrderFilters $filters)
    {

    	$orders = Order::With('client', 'brand', 'product', 'status')
                        ->filter($filters)
                        ->latest('id')
                        ->paginate()
                        ->appends(request()->query());

        return view('orders.index', compact('orders'));
    }

    public function show($order)
    {
    	$order = Order::with('client', 'addresses', 'product', 'brand', 'status')
                        ->find($order);

    	return view('orders.show', compact('order'));
    }
}

app/Http/Controllers/Orders/StatusOrderController.php
<?php

namespace App\Http\Controllers\Orders;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Miyama\Order;
use Miyama\Orders\Statu;

class StatusOrderController extends Controller
{
	protected $status;

	function __construct(Statu $status)
	{
		$this->status = $status;
	}

	public function __invoke(Request $request, Order $order)
	{
    	$this->changeStatu($order);

    	\Alert::info("Su orden a cambiado a {$request->get('statu')}");

    	return redirect()->route('orders.show',['id' => $order->id]);
	}

	public function changeStatu($order)
	{
		return $this->getStatu()->each( function ($statu, $id) use ($order){
			$order->status()->attach($id);
		});
	}

    public function existStatu()
    {
		return $this->getStatu()->contains(request('statu'));
    }

    public function getStatu()
    {
    	return $this->status
					->pluck('slug', 'id');
    }
}

resources/views/orders/create.blade.php
@extends('layouts.template')

@section('page-heading')
<i class="si si-wrench"></i> Nueva Orden 
@endsection

@section('content')
<div class="block block-themed block-rounded">
	<div class="block-">
		<table class="table">
			<thead>
				<tr>
					<th>Identificacion</th>
					<th>Razon Social</th>
					<th>Telefono</th>
					<th>Email</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>{{ $client->full_identification }}</td>
					<td>{{ $client->business_name }}</td>
					<td>{{ $client->mobil }}</td>
					<td>{{ $client->email }}</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

{{ Form::open(['mehtod'=>'POST', 'url' => route('order.generate', ['id' => $client->id]) ]) }}
<div class="block block-rounded">
	<div class="block-header bg-gray-lighter">
		<h3 class="block-title">Informes de la orden</h3>
	</div>
	<div class="block-content">
		<div class="row">
			<div class="col-md-2">
				{!! Field::select('brand_id', $brands) !!}
			</div>
			<div class="col-md-2">
				{!! Field::select('line', $lines) !!}
			</div>
			<div class="col-md-2">
				{!! Field::select('sub_line') !!}
			</div>
			<div class="col-md-2">
				{!! Field::select('product_id') !!}
			</div>
			<div class="col-md-2">
				{!! Field::text('model') !!}
			</div>
			<div class="col-md-2">
				{!! Field::text('serial') !!}
			</div>
		</div>

		<div class="row">
			<div class="col-md-4">
				{!! Field::text('fail') !!}
			</div>
			<div class="col-md-4">
				{!! Field::select('tech_id', $techs) !!}
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="domicilio" class="control-label"> ¿Es a domicilio?</label>
					<div class="controls">
						<label class="css-input switch switch-success">
							No
		                    <input id="domicilio" v-model="addressShow" name="domicilio" type="checkbox"><span></span>
		                    Si
		                </label>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="block" v-show="addressShow">
	<div class="block-header bg-gray-lighter">
	    <h3 class="block-title">Direccion de servicio </h3>
	</div>
	<div class="block-content">
	    <div class="row">
	        <div class="col-lg-6">
	            <!-- Billing Address -->
	            <div class="block block-bordered">
	                <div class="block-header">
	                    <h3 class="block-title">
	                       	<label class="css-input css-radio css-radio-lg css-radio-primary push-10-r">
	                            <input type="radio" name="type_address" checked="" value="{{ optional($client->addresses->first())->id }}"><span></span>
	                    		Direccion Actual
	                        </label>
	                    </h3>
	                </div>
	                <div class="block-content block-content-full">
	                    <div class="h4 push-5">{{ $client->business_name }}</div>
	                    <address>                        	
	                        {!! $client->full_address !!}<br><br>
	                        <i class="fa fa-phone"></i> {{ $client->mobil }}<br>
	                    </address>
	                </div>
	            </div>
	            <!-- END Billing Address -->
	        </div>
	        <div class="col-lg-6">
	            <!-- Shipping Address -->
	            <div class="block block-bordered">
	                <div class="block-header">
	                    <h3 class="block-title">
	                    	<label class="css-input css-radio css-radio-lg css-radio-primary push-10-r">
	                            <input type="radio" name="type_address" value="0"><span></span>
	                    		Otra direccion
	                        </label>
	                    </h3>
	                </div>
	                <div class="block-content block-content-full">
	                    <div class="row">
	                    	<div class="col-md-6">{!! Field::text('person_contact') !!}</div>
	                    	<div class="col-md-6">{!! Field::text('mobil') !!}</div>
	                    </div>
	                    
	                    <div class="row">
	                    	<div class="col-md-6">{!! Field::select('state_id', $states) !!}</div>
	                    	<div class="col-md-6">{!! Field::select('city_id') !!}</div>
	                    </div>

	                    {!! Field::textarea('address', ['rows' => 2]) !!}
	                </div>
	            </div>
	            <!-- END Shipping Address -->
	        </div>
	    </div>
	</div>
</div>

<div class="block">
	<div class="block-content">
		<div class="form-group">
			<button class="btn btn-primary pull-right"><i class="fa fa-save"></i> Guardar</button>
			<button class="btn btn-default"><i class="fa fa-arrow-left"></i> Cancelar</button>
		</div>
	</div>
</div>
{{ Form::close() }}
@endsection

resources/views/orders/filters.blade.php
<div class="block">
	<div class="block-content">
		{{ Form::open(['method' => 'GET']) }}
			<div class="row">
				<div class="col-md-3">
					{!! Field::select('brand', $brands,request('brand')) !!}
				</div>
				<div class="col-md-3">
					{!! Field::text('client', request('client'),['placeholder' => 'Razon Social']) !!}
				</div>
				<div class="col-md-2">
					{!! Field::select('product') !!}
				</div>
				<div class="col-md-2">
					{!! Field::select('statu') !!}
				</div>
				<div class="col-md-2">
					<br>
					<button type="submit" class="btn btn-primary">
						<i class="fa fa-search"></i>
					</button>
				</div>
			</div>
		{{ Form::close() }}
	</div>
</div>

resources/views/orders/index.blade.php
@extends('layouts.template')

@section('page-heading')
	<i class="si si-wrench"></i> Ordenes de Servicios
	<button class="btn btn-success" 
			data-toggle="modal" 
			data-target="#modal-filters" 
			type="button"><i class="fa fa-filter"></i> Filtrar</button>
	@if(request()->fullUrl() != request()->url())
	<a 	href="{{ request()->url() }}"
		class="btn btn-default btn-xs"> 
		Eliminar Filtros
	</a>
	@endif
@endsection

@section('content')

@include('orders.block.header-panel')

<div class="block block-themed block-rounded">
	<div class="block-header bg-primary">
		<h3 class="block-title">Lista de Ordenes</h3>
	</div>
	<div>
	<table class="table table-hover table-condensed">
		<thead>
			<tr>
				<th>#</th>
				<th>Fecha</th>
				<th>Cliente</th>
				<th>Marca</th>
				<th>Producto</th>
				<th>Estatus</th>
				<th>Tipo</th>
				<th>Accion</th>
			</tr>
		</thead>
		<tbody>
			@forelse($orders as $order)

				<tr>
					<td>{{ $order->id }}</td>
					<td>{{ $order->created_at->diffForHumans() }}</td>
					<td><a href="{{ route('clients.show', [ 'id'=> $order->client->id ]) }}">{{ $order->client->business_name }}</a></td>
					<td>{{ $order->brand->name }}</td>
					<td>{{ $order->product->name }}</td>
					<td>
						{!! $order->statu !!}
					</td>
					<td>{{ __($order->type) }}</td>
					<td>
						<div class="btn-group">
							<a href="{{ route('orders.show', ['id' => $order->id]) }}" class="btn btn-primary btn-xs">
								<i class="fa fa-eye"></i>
							</a>
							@can('revisar', $order)
							<a href="{{ route('order.statu', ['id' => $order->id, 'statu' => 'revision']) }}" class="btn btn-success btn-xs">
								Revisar
							</a>
							@endcan
						</div>
					</td>
				</tr>
			@empty

			<tr class="alert alert-danger">
				<td colspan="7">
					No seencontro registro en esta busqueda!
				</td>
			</tr>

			@endforelse
		</tbody>
	</table>
		{!! $orders->links() !!}
	</div>
</div>


{{-- Modal Filter --}}

@include('orders.block.filters-modal')

@endsection

resources/views/orders/presupuestar.blade.php
<div class="modal fade" id="presupuestar">
	<div class="modal-dialog  modal-dialog-slideleft modal-lg">
		<div class="modal-content">
			<div class="block block-rounded block-themed block-transparent remove-margin-b">
				<div class="block-header bg-primary-dark">
					<ul class="block-options">
                        <li>
                            <button data-dismiss="modal" type="button"><i class="si si-close"></i></button>
                        </li>
                    </ul>
					<h3 class="block-title">
						Presupuestar
						<button class="btn btn-success btn-sm"><i class="si si-plus"></i> Nueva Partida</button>
					</h3>
				</div>
				<div>
					<table-presupuesto />
				</div>
			</div>
			<div class="modal-footer">
				<button class="btn btn-primary">Guardar</button>
			</div>
		</div>
	</div>
</div>

resources/views/orders/show.blade.php
@extends('layouts.template')

@section('page-heading')
<i class="si si-wrench"></i> Orden # {{ $order->id }}
@endsection

@section('content')

<div class="row">
	<div class="col-md-12" id="info">
		<div class="block block-rounded">
			<div class="block-header bg-gray">
				<h4 class="block-title">
					Informacion Cliente
				</h4>
			</div>
			<div>
				<table class="table table-condensed">
					<tbody>
						<tr>
							<th>Indentificacion</th>
							<th>Razon Social</th>
							<th>Telefonos</th>
							<th colspan="2">Email</th>
						</tr>
						<tr>
							<td>{{ $order->client->full_identification }}</td>
							<td>{{ $order->client->business_name }}</td>
							<td>{{ $order->client->mobil }}</td>
							<td colspan="2">{{ $order->client->email }}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-12">
		<div class="block block-rounded">
			<div class="block-header bg-gray">
				<h4 class="block-title">
					Informacion de la orden
					{!! $order->statu !!}
				</h4>
			</div>
			<div>
				<table class="table table-condensed">
					<tbody>
						<tr>
							<th>Marca</th>
							<th>Linea</th>
							<th>Sub Linea</th>
							<th>Modelo</th>
							<th>Producto</th>
						</tr>
						<tr>
							<td>{{ $order->brand->name }}</td>
							<td>{{ $order->product->sub_line->line->name }}</td>
							<td>{{ $order->product->sub_line->name }}</td>
							<td>{{ $order->model }}</td>
							<td>{{ $order->product->name }}</td>
						</tr>
						<tr>
							<th>Tipo de Orden</th>
							<th colspan="4">Direccion</th>
						</tr>
						<tr>
							<td>{{ __($order->type) }}</td>
							<td colspan="4">{!! $order->full_address !!}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<!--Time Line Component(Migrar VUEJS-->
</div>

<div class="row">
	@include('orders.block.time-line')
	@include('orders.block.presupuesto')
</div>

@include('orders.presupuestar')

@endsection